name: Accessibility tests

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      tests:
        description: 'Tests to run (leave blank to run all tests!)'
        required: false
        default: ''
      device:
        description: 'Device to test'
        required: true
        default: 'Desktop Chrome'
        type: choice
        options:
          - Desktop Chrome
          - Desktop Edge
          - Desktop Firefox
          - Desktop Safari
          - Galaxy S9+
          - Pixel 7
          - iPad (gen 7) landscape
          - iPhone 15
      environment:
        description: Environment to run tests on
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - training
          - sandbox-alpha
          - sandbox-beta
      screenshot_all_steps:
        description: Take screenshots for all steps (in addition to failures)
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      set_feature_flags:
        description: >-
          Set feature flags in the flipper page before running tests (affects all
          users of the environment being tested!)
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      additional_feature_flags:
        description: >-
          (If enabled above) Additional feature flags to set. api, basic_auth,
          dev_tools will be set by default
        required: false
        default: ''

jobs:
  test:
    permissions:
      contents: write
      id-token: write

    name: End-to-End tests
    runs-on: ubuntu-latest

    env:
      TZ: "Europe/London"

    steps:
      # yamllint disable rule:line-length
      - name: Set variables
        id: set-variables
        run: |
          declare -A env_map=(
            [qa]="https://qa.mavistesting.com"
            [training]="https://training.manage-vaccinations-in-schools.nhs.uk"
            [sandbox-alpha]="https://sandbox-alpha.mavistesting.com"
            [sandbox-beta]="https://sandbox-beta.mavistesting.com"
          )
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "schedule" ]]; then
            {
              echo "tests="
              echo "device=Desktop Chrome"
              echo "environment=${env_map[qa]}"
              echo "set_feature_flags=false"
              echo "additional_feature_flags="
              echo "screenshot_all_steps=false"
          } >> "$GITHUB_OUTPUT"
          else
            {
              echo "tests=${{ github.event.inputs.tests }}"
              echo "device=${{ github.event.inputs.device }}"

              input_env="${{ github.event.inputs.environment }}"
              url="${env_map[$input_env]:-${env_map[qa]}}"
              echo "environment=$url"

              echo "set_feature_flags=${{ github.event.inputs.set_feature_flags }}"
              echo "additional_feature_flags=${{ github.event.inputs.additional_feature_flags }}"
              echo "screenshot_all_steps=${{ github.event.inputs.screenshot_all_steps }}"
            } >> "$GITHUB_OUTPUT"
          fi
      # yamllint enable rule:line-length

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Deployment health check
        uses: ./.github/actions/deployment-health-check
        with:
          environment_url: ${{ steps.set-variables.outputs.environment }}

      - name: Cache Playwright browsers
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: playwright-cache
        with:
          path: /home/runner/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Run tests
        uses: ./.github/actions/run-end-to-end-tests
        with:
          tests: ${{ steps.set-variables.outputs.tests }}
          accessibility_tests: 'true'
          device: ${{ steps.set-variables.outputs.device }}
          base_url: ${{ steps.set-variables.outputs.environment }}
          screenshot_all_steps: ${{ steps.set-variables.outputs.screenshot_all_steps }}
          set_feature_flags: ${{ steps.set-variables.outputs.set_feature_flags }}
          additional_feature_flags: >-
            ${{ steps.set-variables.outputs.additional_feature_flags }}
          playwright_cache_hit: ${{ steps.playwright-cache.outputs.cache-hit }}
        env:
          BASIC_AUTH_TOKEN: ${{ secrets.HTTP_AUTH_TOKEN_FOR_TESTS }}
          IMMS_BASE_URL: ${{ vars.IMMS_BASE_URL }}
          IMMS_API_KEY: ${{ secrets.IMMS_API_KEY }}
          IMMS_API_KID: ${{ secrets.IMMS_API_KID }}
          IMMS_API_PEM: ${{ secrets.IMMS_API_PEM }}

      - name: Configure AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::393416225559:role/GitHubAssuranceTestRole

      - name: Process reports
        if: always()
        uses: ./.github/actions/deploy-reports
        with:
          device: ${{ steps.set-variables.outputs.device }}
          environment: ${{ github.event.inputs.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
